"""Infrastructure domain runtime entrypoint."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from a0.components.infrastructure.ops_planner import build_operation_plan  # noqa: E402
from a0.components.infrastructure.contracts import domain_boundaries, handoff_contracts  # noqa: E402
from a0.components.infrastructure.agent_profile_builder import scaffold_agent_profile, validate_scaffold  # noqa: E402
from a0.components.infrastructure.dev_security_ops import developer_ops_plan, security_ops_plan  # noqa: E402
from a0.components.infrastructure.readiness_checks import evaluate_readiness  # noqa: E402
from a0.components.infrastructure.safety_gates import assess_risks  # noqa: E402


def execute_ops(target: str, environment: str, mode: str = "standard") -> dict[str, object]:
    checks = evaluate_readiness(environment)
    operation_plan = build_operation_plan(target, environment)
    risks = assess_risks(checks)
    extras: dict[str, object] = {}
    if mode == "agent-build":
        scaffold = scaffold_agent_profile(
            name="new-agent",
            title="New Agent",
            description="Generated by infrastructure agent-build mode.",
            domain="general",
        )
        extras["agent_profile_scaffold"] = scaffold
        extras["agent_profile_validation"] = validate_scaffold(scaffold)
    elif mode == "security":
        extras["security_ops"] = security_ops_plan(scope=target)
    elif mode == "developer":
        extras["developer_ops"] = developer_ops_plan(task_type="feature")
    return {
        "target": target,
        "environment": environment,
        "mode": mode,
        "checks": checks,
        "operation_plan": operation_plan,
        "risks": risks,
        "ownership": domain_boundaries(),
        "handoff_contracts": handoff_contracts(),
        "extras": extras,
        "ready": all(checks.values()),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Execute deterministic infrastructure operations.")
    parser.add_argument("--target", default="application")
    parser.add_argument("--environment", default="staging")
    parser.add_argument("--mode", default="standard", choices=["standard", "agent-build", "security", "developer"])
    args = parser.parse_args()
    print(json.dumps(execute_ops(args.target, args.environment, args.mode), indent=2))


if __name__ == "__main__":
    main()
